version: "2"

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otelcol.yaml"]
    volumes:
      - ./otelcol.yaml:/etc/otelcol.yaml
    ports:
      - "1888:1888"  # pprof extension
      - "8888:8888"  # Prometheus metrics exposed by the collector
      - "8889:8889"  # Prometheus exporter metrics
      - "13133:13133"  # health_check extension
      - "4317:4317"  # OTLP gRPC receiver
      - "55679:55679"  # zpages extension
      - "4318:4318"  # OTLP HTTP receiver
      
  prometheus:
    image: quay.io/prometheus/prometheus:v2.34.0
    command: --config.file=/etc/prometheus.yaml --no-scrape.adjust-timestamps
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"